---
title: "Incivility and Representation"
subtitle: Abbildungen und Tabellen
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
bibliography: literatur.bibtex
always_allow_html: yes
editor_options:
  chunk_output_type: console
---

```{r load_libraries, message = FALSE, echo = FALSE}
library(data.table)
library(dplyr)
library(magrittr)
library(tidyr)
library(forcats)
library(haven)
library(crosstable)
library(scales)
library(ggplot2)
library(flextable)
library(openxlsx)
library(ggplot2)
library(kommrep)
library(xtable)
library(stargazer)
library(jtools)
library(broom.mixed) # to avoid later msg of loading
library(officer)
library(ggpubr)
library(kableExtra)
```

```{r check_kommrep_version, echo = FALSE}
stopifnot(packageVersion("kommrep") >= package_version("0.4.7"))
```

```{r make modified_table, echo = FALSE, results = "asis"}
kommrep_loc_lm <- kommrep_loc %>%
  
  mutate(across(v_perzb_art1:v_perzb_art5, ~ as.vector(.))) %>% 
  mutate(across(v_perzb_art1:v_perzb_art5, ~ ifelse(. == 98, NA, .))) %>% 
  mutate(across(v_perzb_art1:v_perzb_art5, ~ . - 1)) %>% 
  mutate(across(v_perzb_art1:v_perzb_art5, ~ as.logical(.))) %>% 
  rowwise() %>% 
  mutate(`kommunikative Inzivilität` = any(c_across(v_perzb_art1:v_perzb_art2), na.rm = TRUE)) %>% 
  mutate(`physische Inzivilität` = any(c_across(v_perzb_art3:v_perzb_art5), na.rm = TRUE)) %>% 
  ungroup() %>% 

  mutate(threat_experience = ifelse(as.vector(v_bedrohung) == 1L, TRUE, FALSE)) %>% 

  mutate(age = 2022 - v_alter) %>%
  mutate(age = age - min(age, na.rm = TRUE)) %>% 
  mutate(age = age / max(age, na.rm = TRUE)) %>% 
  
  mutate(AfD = ifelse(party == "AfD", TRUE, FALSE)) %>%
  mutate(CDU = ifelse(party == "CDU", TRUE, FALSE)) %>%
  mutate(CSU = ifelse(party == "CSU", TRUE, FALSE)) %>%
  mutate(FW = ifelse(party == "Freie Wähler", TRUE, FALSE)) %>%
  mutate(LINKE = ifelse(party == "Die Linke", TRUE, FALSE)) %>%
  mutate(GRUENE = ifelse(party == "Bündnis 90/Die Grünen", TRUE, FALSE)) %>%
  mutate(SPD = ifelse(party == "SPD", TRUE, FALSE)) %>%
  
  mutate(asian = as.logical(as.integer(as.factor(v_out3_mmh)) - 1) | as.logical(as.integer(as.factor(v_out3_mkm)) - 1)) %>%	# Asiatisch
  mutate(asian = ifelse(is.na(asian), FALSE, asian)) %>% 
  
  mutate(jewish = as.logical(as.integer(as.factor(v_out4_mmh)) - 1) | as.logical(as.integer(as.factor(v_out4_mkm)) - 1)) %>%	# Jüdisch
  mutate(jewish = ifelse(is.na(jewish), FALSE, jewish)) %>% 
  
  mutate(muslim = as.logical(as.integer(as.factor(v_out5_mmh)) - 1)| as.logical(as.integer(as.factor(v_out5_mkm)) - 1)) %>%	# Muslimisch
  mutate(muslim = ifelse(is.na(muslim), FALSE, muslim)) %>% 
  
  mutate(sintiroma = as.logical(as.integer(as.factor(v_out6_mmh)) - 1) | as.logical(as.integer(as.factor(v_out6_mkm)) - 1)) %>%	# Sinti oder Roma
  mutate(sintiroma = ifelse(is.na(sintiroma), FALSE, sintiroma)) %>% 
  
  mutate(turkish = as.logical(as.integer(as.factor(v_out7_mmh)) - 1)| as.logical(as.integer(as.factor(v_out7_mkm)) - 1)) %>%	# Türkisch
  mutate(turkish = ifelse(is.na(turkish), FALSE, turkish)) %>% 
  
  mutate(eastern = as.logical(as.integer(as.factor(v_out8_mmh)) - 1) | as.logical(as.integer(as.factor(v_out8_mkm)) - 1)) %>%	# Osteuropäisch
  mutate(eastern = ifelse(is.na(eastern), FALSE, eastern)) %>% 
  
  mutate(black = as.logical(as.integer(as.factor(v_out9_mmh)) - 1)| as.logical(as.integer(as.factor(v_out9_mkm)) - 1)) %>%	# Schwarze Person
  mutate(black = ifelse(is.na(black), FALSE, black)) %>% 
  
  mutate(muslim_turkish = muslim | turkish) %>% 
  
  mutate(racialized = asian | jewish | muslim | sintiroma | turkish | eastern | black) %>% 
  
  # Exit / Rückzugsgedanken (für deskriptive Repräsentation)
  mutate(v_exit = ifelse(v_exit == 98, NA, v_exit)) %>% 
  mutate(Rückzugsgedanke = ifelse(v_exit == 1, TRUE, FALSE)) %>%
  mutate(Rückzugsgedanke = ifelse(is.na(Rückzugsgedanke), FALSE, Rückzugsgedanke)) %>%

  # Themenvermeidung (für substantielle Repräsentation)
  mutate(Themenvermeidung = ifelse(v_sorge_umgang4 == 1L, TRUE, FALSE)) %>%
  mutate(Themenvermeidung = ifelse(is.na(Themenvermeidung), FALSE, Themenvermeidung)) %>% 

  mutate(female_diverse = as_factor(v_geschlecht)) %>% 
  mutate(female_diverse = recode(
    female_diverse,
    `weiblich` = "TRUE",
    `männlich` = "FALSE",
    `divers` = "TRUE",
    `weitere / andere` = "TRUE"
  )) %>%
  mutate(female_diverse = as.logical(female_diverse)) %>%
  
  mutate(class_normalized = ifelse(as.vector(v_schicht) != 98, ((v_schicht - 1L) / 5L) * -1 + 1, NA)) %>%
  
  mutate(`class` = as_factor(v_schicht)) %>%
  mutate(
    `class` = recode(
      `class`,
      `Der Oberschicht` = "upper",
      `Der oberen Mittelschicht` = "upper",
      `Der Mittelschicht` = "middle",
      `Der unteren Mittelschicht` = "lower",
      `Der Arbeiterschicht` = "lower",
      `Der Unterschicht` = "lower",
      `Weiß nicht` = "dont't know / not available"
    )
  ) %>%
  mutate(`class` = fct_na_value_to_level(`class`, level = "dont't know / not available")) %>%
  
  mutate(class_lower = ifelse(class == "lower", TRUE, FALSE)) %>% 
  
  mutate(class_num = as.vector(v_schicht)) %>% 
  mutate(class_num = ifelse(class_num > 6, NA, class_num)) %>% 
  mutate(class_num = (class_num - 1) / 5)
```

```{r set_options, include = FALSE}
options("modelsummary_format_numeric_latex" = "plain")
```


## Anteile UVs

```{r plain_shares, results = "asis", echo=FALSE}
kommrep_loc_lm %>%
  select(
    `kommunikative Inzivilität`, 
    `physische Inzivilität`,
    # threat_verbal,
    # threat_physical,
    # threat_verbal_bin,
    # threat_physical_bin,
    female_diverse,
    class,
    racialized,
    weight_ps
  ) %>%
  # select(-threat_verbal, -threat_physical) %>%
  
  mutate(class_lower = ifelse(class == "lower", TRUE, FALSE)) %>%
  
  mutate(across(everything(), as.vector)) %>%
  pivot_longer(
    cols = c(
      `kommunikative Inzivilität`,
      `physische Inzivilität`,
#      threat_verbal_bin,
# threat_physical_bin,
      racialized,
      female_diverse,
      class_lower # untere Mittelschächer und darunter
    )
  ) %>%
  group_by(name, value) %>%
  summarise(n = n(), n_weighed = sum(weight_ps), .groups = "rowwise") %>%
  select(-n) %>%
  pivot_wider(names_from = value, values_from = c(n_weighed)) %>%
  ungroup() %>%
  mutate(total = apply(as.matrix(select(., `FALSE`, `TRUE`, `NA`)), 1, sum, na.rm = TRUE)) %>%
  mutate(
    true = round(`TRUE` / total * 100, 1),
    na = round(`NA` / total * 100, 1),
    false = round(`FALSE` / total * 100, 1)
  ) %>%
  mutate(missing = ifelse(is.na(na), 0, na)) %>%
  select(name, true, missing, false) %>%
  mutate(variable = as.factor(name)) %>%
  select(-name) %>%
  mutate(variable = forcats::fct_recode(
    variable,
#    `kommunikative Inzivilität` = "threat_verbal_bin",
 # `physische Inzivilität` = "threat_physical_bin",
    `migrantisierte Gruppe` = "racialized",
    `weiblich oder divers` = "female_diverse",
    `niedrigere Schichtzugehörigkeit` = "class_lower"
  )) %>%
  mutate(
    variable = factor(
      variable,
      levels = c(
        "kommunikative Inzivilität",
        "physische Inzivilität",
        "migrantisierte Gruppe",
        "weiblich oder divers",
        "niedrigere Schichtzugehörigkeit"
      )
    )
  ) %>%
  mutate(
    ja = paste0(true, "%"),
    `w.n./k.A.` = paste0(missing, "%"),
    nein = paste0(false, "%")
  ) %>%
  select(-true, -missing, -false) %>% 
  mutate(`w.n./k.A.` = ifelse(`w.n./k.A.` == "0%", "---", `w.n./k.A.`)) %>%
  arrange(variable) %>%
  relocate(variable) %>% 
  rename(`UV` = "variable") %>% 
  as_flextable(show_coltype = FALSE) %>%
  add_footer_lines("* Berechnung der Anteilswerte mit Gewichtung")
```

\newpage

## Inzivilitätserfahrungen

```{r beleidigt, echo = FALSE, results = "asis"}
kommrep_loc %>%
  select(v_bedrohung, v_geschlecht, v_mig_background, db_bundesland) %>%
  mutate(threat = as_factor(v_bedrohung)) %>%
  mutate(threat = recode(
    threat,
    `Weiß nicht` = "weiß nicht / keine Antwort",
    `Ja` = "ja", `Nein` = "nein"
    )
  ) %>%
  mutate(threat = replace_na(threat, "weiß nicht / keine Antwort")) %>% 
  group_by(threat) %>%
  summarise(N = n()) %>%
  mutate(percent = N / sum(N)) %>% 
  xtable()
```

\newpage

## Types of incivility by sex, class, migration background, party

```{r, echo = FALSE, fig.width = 8, warning = FALSE}
attacks <- kommrep_loc %>%
  
  select(
    starts_with("v_perzb_art"),
    v_geschlecht,
    v_mig_background,
    v_schicht,
    v_part1
  ) %>%
  
  select(
    -v_perzb_art7, # Art der der Bedrohung: Andere Erfahrungen 
    -v_perzb_art6 # Art der der Bedrohung (offen)
  ) %>%
  
  mutate(across(starts_with("v_perzb_art"), as_factor)) %>%
  mutate(across(starts_with("v_perzb_art"), recode, `Trifft zu` = "yes", `Trifft nicht zu` = "no", `Weiß nicht` = "don't know / no reply")) %>%
  mutate(across(starts_with("v_perzb_art"), as.character)) %>%
  mutate(across(starts_with("v_perzb_art"), replace_na, "don't know / no reply")) %>%
  mutate(across(starts_with("v_perzb_art"), as.factor)) %>%
  
  mutate(sex = as_factor(v_geschlecht)) %>%
  mutate(sex = recode(sex, `divers` = "nonbinary", `weitere / other` = "nonbinary")) %>%
  
  mutate(`migration background` = ifelse(v_mig_background, "yes", "no")) %>%

  mutate(class = as_factor(v_schicht)) %>%
  mutate(
    class = recode(
      class,
      `Der Oberschicht` = "high",
      `Der oberen Mittelschicht` = "high",
      `Der Mittelschicht` = "medium",
      `Der unteren Mittelschicht` = "low",
      `Der Arbeiterschicht` = "low",
      `Der Unterschicht` = "low"
    )) %>%
  mutate(class = na_if(class, "Weiß nicht")) %>%
  mutate(class = droplevels(class)) %>%
  
  mutate(Partei = as.character(as_factor(v_part1))) %>%
  
  select(-v_geschlecht, -v_mig_background, -v_schicht, v_part1) %>%
  rename(
    LegacyComm = v_perzb_art1,
    SocMedia = v_perzb_art2,
    Encounter = v_perzb_art3,
    Damage = v_perzb_art4,
    Attack = v_perzb_art5
  ) %>%
  mutate(across(everything(), function(x) as.vector(x)))


what <- c("LegacyComm", "SocMedia", "Encounter", "Damage", "Attack")
ctbs <- lapply(
  what,
  function(var){
    attacks %>%
      select(all_of(var), sex, class, `migration background`, Partei) %>%
      crosstable(
        by = all_of(var),
        total = "both",
        percent_digits = 1,
        percent_pattern = list(
          body = "{n}\n({p_row})",
          total_row = "{n}\n({p_row})",
          total_col = "{n}\n({p_row})",
          total_all = "{n}\n({p_row})"
        ),
        showNA = "no"
      ) 
  }
)
names(ctbs) <- what

tab <- bind_cols(
  select(ctbs[[1]], -yes, -no, -`don't know / no reply`, -Total),
  as_tibble(as.data.frame(lapply(ctbs, `[[`, "yes"))),
  select(ctbs[[1]], Total)
)
total_row <- filter(tab, variable == "Total")[1,]
total_row[1,2:3] <- "Total"
tab <- bind_rows(
  filter(tab, variable != "Total"),
  total_row
)

as_flextable(
  tab,
  fontsizes = list(body = 8, subheaders = 8, header = 8)
)
```

\newpage

## Folgen von Inzivilitätsformen

```{r threat_and_change4, echo = FALSE}
.data <- lapply(
  c("Rückzugsgedanke", "Themenvermeidung"),
  function(effect_type){
    lapply(
      c("kommunikative Inzivilität", "physische Inzivilität"),
      function(incivility_type){
        .data <- kommrep_loc_lm %>%
          select(all_of(effect_type), all_of(incivility_type), weight_ps) %>%
          group_by(!!sym(effect_type), !!sym(incivility_type)) %>%
          summarise(n_weighed = sum(weight_ps), n = n(), .groups = "rowwise") %>%
          group_by(!!sym(incivility_type)) %>% 
          reframe(
            `behavioral effect` = !!sym(effect_type),
            n_weighed = n_weighed,
            share = n_weighed / sum(n_weighed)
          ) %>%
          mutate(behavior = effect_type) %>%
          mutate(threat = incivility_type) %>%
          rename(`threat applicable` = all_of(incivility_type))
        
        chitest <- .data %>%
          select(`behavioral effect`, `threat applicable`, n_weighed) %>% 
          pivot_wider(names_from = `threat applicable`, values_from = n_weighed) %>% 
          select(-`behavioral effect`) %>% 
          as.matrix() %>% 
          chisq.test()
        
        .data %>% 
          mutate(X = chitest[["statistic"]], p = chitest[["p.value"]]) %>% 
          mutate(
            sig = if (chitest[["p.value"]] < 0.001) "p < 0.001"
              else if (chitest[["p.value"]] < 0.01) "p < 0.01"
              else if (chitest[["p.value"]] < 0.05) "p < 0.05"
              else "p >= 0.05"
          )

      }
    )
  }
) %>% 
  bind_rows()

.data %>%
  filter(`behavioral effect` == TRUE) %>% 
  mutate(`threat applicable` = ifelse(`threat applicable`, "ja", "nein")) %>% 
  mutate(`threat applicable` = factor(`threat applicable`, levels = c("nein", "ja"))) %>% 
  ggplot(aes(x = `threat applicable`, y = share, fill = `behavioral effect`)) +
    geom_bar(position = "stack", stat = "identity", fill = "steelblue") +
    facet_grid(behavior ~ threat) +
    geom_text(
      aes(label = paste(round(share * 100, 1), "%")),
      position = position_stack(0.5),
      color = "white"
    ) +
    scale_y_continuous(labels = scales::label_percent()) +
    ylab("Anteil in Prozent (gewichtete Werte)") +
    xlab("Bedrohungserfahrung kommunikative / physische Inzivilität") +
    theme(legend.position = "none") +
    geom_text(
      aes(
        label = sprintf("\u03C7\u00B2 = %s\n%s", round(X, 2), sig),
        x = 1,
        y = 0.12
      )
    )

ggsave("~/Lab/github/incivility/svg/incivility_and_representation.svg", width = 24, height = 12, units = "cm")
```



\newpage

## Effekte von Inzivilität nach Gruppen

```{r groups_and_effects, echo = FALSE}
.data <- lapply(
  c("Rückzugsgedanke", "Themenvermeidung"),
  function(effect_type){
    lapply(
      c("racialized", "female_diverse", "class_lower"),
      function(soc_group){
        .data <- kommrep_loc_lm %>%
          select(all_of(soc_group), all_of(effect_type), weight_ps) %>%
          rename(`social group` = all_of(soc_group)) %>%
          rename(`effect type` = all_of(effect_type)) %>% 
          mutate(`social group` = ifelse(is.na(`social group`), FALSE, `social group`)) %>% 
          group_by(`social group`, `effect type`) %>%
          summarise(n_weighed = sum(weight_ps), n = n(), .groups = "rowwise") %>%
          mutate(group = soc_group) %>%
          mutate(effect = effect_type) %>%
          ungroup() %>%
          group_by(`social group`) %>% 
          reframe(
            share = n_weighed / sum(n_weighed),
            `effect type` = `effect type`,
            n_weighed = n_weighed,
            n = n,
            group = group,
            effect = effect
          ) %>% 
          ungroup()

        
        chitest <- .data %>%
          select(`social group`, `effect type`, n_weighed) %>% 
          pivot_wider(names_from = `effect type`, values_from = n_weighed) %>% 
          select(-`social group`) %>% 
          as.matrix() %>% 
          chisq.test()
        
        .data_min <- .data %>% 
          filter(`effect type` == TRUE)
        
        .data_min %>% mutate(
            X = chitest[["statistic"]],
            p = chitest[["p.value"]],
            share_max = max(share)
          ) %>% 
          mutate(
            sig = if (chitest[["p.value"]] < 0.001) "p < 0.001"
              else if (chitest[["p.value"]] < 0.01) "p < 0.01"
              else if (chitest[["p.value"]] < 0.05) "p < 0.05"
              else "p >= 0.05"
          )
      }
    )
  }
) %>% 
  bind_rows()

.data %>%
  mutate(`social group` = ifelse(`social group`, "ja", "nein")) %>% 
  mutate(`social group` = factor(`social group`, levels = c("nein", "ja"))) %>% 
  mutate(effect = factor(effect, levels = c("Themenvermeidung", "Rückzugsgedanke"))) %>% 
  ggplot(aes(x = `social group`, y = share)) +
    geom_bar(position = "dodge", stat = "identity", fill = "steelblue") +
    facet_grid(group ~ effect) +
    geom_text(
      aes(label = paste(round(share * 100, 1), "%")),
      position = position_stack(0.5),
      color = "white"
    ) +
    scale_y_continuous(labels = scales::label_percent()) +
    ylab("Anteil in Prozent (gewichtete Werte)") +
    xlab("Zugehörigkeit zu sozialen Gruppen und Verhaltenseffekte aus Sorge vor Bedrohungen") +
    theme(legend.position = "none") +
    geom_text(
      aes(label = sprintf("\u03C7\u00B2 = %s\n%s", round(X, 2), sig ), x = 1, y = .12),
      size = 3
    )

ggsave("~/Lab/github/incivility/svg/groups_and_representation.svg", width = 24, height = 12, units = "cm")
```

\newpage

```{r}
parties <- c("AfD", "CDU", "CSU", "FDP", "SPD", "Bündnis 90/Die Grünen", "Die Linke")

lapply(
  c("Rückzugsgedanke", "Themenvermeidung"),
  function(effect){
    kommrep_loc_lm %>% 
      select(
        all_of(effect),
        party,
        weight_ps
      ) %>% 
      group_by(party) %>% 
      summarise(
        share = sum(!!sym(effect) * weight_ps) / sum(weight_ps),
        N = n()
      ) %>% 
      mutate(effect = effect)
  }
) %>% 
  bind_rows() %>% 
  filter(party %in% parties) %>% 
  mutate(party = factor(party, levels = parties)) %>% 
  mutate(party = fct_recode(
    party,
    `Grüne` = "Bündnis 90/Die Grünen",
    `Linke` = "Die Linke"
  )) %>% 
  ggplot(aes(x = party, y = share)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(
    aes(label = sprintf("%s\nN=%d", paste(round(share * 100, 1), "%"), N)),
    position = position_stack(0.5),
    color = "white",
    size = 2
    
  ) +
  scale_y_continuous(labels = scales::label_percent()) +
  facet_grid(~ effect) + 
  ylab("prozentualer Anteil") +
  xlab(element_blank())


```

\newpage

##

```{r descriptive_representation, results = "asis", echo = FALSE}
kommrep_loc_lm_min <- kommrep_loc_lm 
# %>%
#   filter(threat_experience == TRUE)

exit1 <- glm(
  Rückzugsgedanke ~ `kommunikative Inzivilität` + `physische Inzivilität`,
  data = kommrep_loc_lm_min,
  family = binomial("logit")
)

exit2 <- glm(
  Rückzugsgedanke ~ `kommunikative Inzivilität` + `physische Inzivilität` +
         female_diverse + class_num + racialized,
  data = kommrep_loc_lm_min,
  family = binomial("logit")
)

exit3 <- glm(
  Rückzugsgedanke ~ `kommunikative Inzivilität` + `physische Inzivilität` +
         female_diverse + class_num + racialized +
         age +
         AfD + SPD + GRUENE + LINKE,
  data = kommrep_loc_lm_min,
  family = binomial("logit")
)

modelsummary::modelsummary(
  models = list(
    A = exit1,
    B = exit2,
    C = exit3
  ),
  estimate = "{estimate} ({std.error}){stars}",
  statistic = NULL,
  output = "latex",
  coef_map = c(
    "kommunikative InzivilitätTRUE" = "kommunikative Inzivilität",
    "physische InzivilitätTRUE" = "physische Inzivilität",
    # "threat_verbal" = "kommunikative Inzivilität",
    # "threat_physical_binTRUE" = "physische Inzivilität",
    "racializedTRUE" = "migrantisierte Gruppe (Ref. nein)",
    "female_diverseTRUE" = "weiblich oder divers (Ref. nein)",
    "class_num" = "Schichtzugehörigkeit",
    "AfDTRUE" = "AfD (Ref. other)",
    "SPDTRUE" = "SPD",
    "GRUENETRUE" = "B'90/Grüne",
    "LINKETRUE" = "LINKE",
    "age" = "Age",
    "(Intercept)" = "(Intercept)"
  ),
  stars = c('*' = .05, '**' = .01, '***' = .001),
  title = "Effekte von Inzivilität auf deskriptive Repräsentation: Rückzugsgedanken"
  # , gof_omit = "BIC|AIC|RMSE|Log.Lik|F"
)
```

\newpage

##

```{r, results = "asis", echo = FALSE}
muted1 <- glm(
  Themenvermeidung ~ `kommunikative Inzivilität` + `physische Inzivilität`,
  data = kommrep_loc_lm_min,
  family = binomial("logit")
)

muted2 <- glm(
  Themenvermeidung ~ `kommunikative Inzivilität` + `physische Inzivilität` +
         female_diverse + class_num + racialized,,
  data = kommrep_loc_lm_min,
  family = binomial("logit")
)

muted3 <- glm(
  Themenvermeidung ~ `kommunikative Inzivilität` + `physische Inzivilität` +
         female_diverse + class_num + racialized +
         age +
         AfD + SPD + GRUENE + LINKE,
  data = kommrep_loc_lm_min,
  family = binomial("logit")
)

modelsummary::modelsummary(
  models = list(A = muted1, B = muted2, C = muted3),
  estimate = "{estimate} ({std.error}){stars}",
  statistic = NULL,
  output = "latex",
  coef_map = c(
    "kommunikative InzivilitätTRUE" = "kommunikative Inzivilität",
    "physische InzivilitätTRUE" = "physische Inzivilität",
    "racializedTRUE" = "migrantisierte Gruppe (Ref. nein)",
    "female_diverseTRUE" = "weiblich oder divers (Ref. nein)",
    "class_num" = "Schichtzugehörigkeit",
    "AfDTRUE" = "AfD (Ref. other)",
    "SPDTRUE" = "SPD",
    "GRUENETRUE" = "B'90/Grüne",
    "LINKETRUE" = "LINKE",
    "age" = "Age",
    "(Intercept)" = "(Intercept)"
  ),
  stars = c('*' = .05, '**' = .01, '***' = .001),
  title = "Effekte von Inzivilität auf substantielle Repräsentation: Themenvermeidung"
#  , gof_omit = "BIC|AIC|RMSE|Log.Lik|F"
)
```

