---
title: "Threat Experiences"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
bibliography: literatur.bibtex
always_allow_html: true
classoption: landscape
editor_options: 
  chunk_output_type: console
---

```{r load_libraries, message = FALSE, echo = FALSE}
library(dplyr)
library(data.table)
library(xts)
library(haven)
library(magrittr)
library(tidyr)
library(xtable)
library(forcats)
library(scales)
library(crosstable)
library(stargazer)
library(jtools)
library(broom.mixed) # to avoid later msg of loading
library(ggplot2)
library(flextable)
library(officer)
library(scales)
library(stargazer)
library(openxlsx)

library(kommrep)
stopifnot(packageVersion("kommrep") >= package_version("0.3.8"))
```

```{r set_options, include = FALSE}
set_flextable_defaults(pct_digits = "#")
options("modelsummary_format_numeric_latex" = "plain")
```


\newpage

## Threat experiences

```{r beleidigt, echo = FALSE, results = "asis"}
kommrep_loc_min <- kommrep_loc %>%
  select(v_bedrohung, v_geschlecht, v_mig_background, db_bundesland) %>%
  mutate(threat = as_factor(v_bedrohung)) %>%
  mutate(threat = recode(
    threat,
    `Weiß nicht` = "don't know / no response",
    `Ja` = "yes", `Nein` = "no"
    )
  ) %>%
  mutate(threat = replace_na(threat, "don't know / no response"))
  

kommrep_loc_min %>% 
  group_by(threat) %>%
  summarise(N = n()) %>%
  mutate(percent = N / sum(N)) %>%
  ggplot(aes(x = threat, y = percent, label = N)) + 
  geom_bar(stat = "identity") + 
  geom_text(
     position = position_dodge(width = .9),    # move to center of bars
     vjust = -0.5,    # nudge above top of bar
     size = 3
  ) + 
  scale_y_continuous(labels = scales::percent) +
  xlab("threat experience")
```


\newpage

## Threat experiences by sex, class, migration background

```{r, echo = FALSE}
threatened1 <- kommrep_loc %>%
  
  select(v_bedrohung, v_geschlecht, v_mig_background, v_schicht) %>%
  
  mutate(`threat experience` = as_factor(v_bedrohung)) %>%
  mutate(`threat experience` = recode(
    `threat experience`,
    `Weiß nicht` = "don't know / no response",
    `Ja` = "yes", `Nein` = "no"
    )
  ) %>%
  mutate(
    `threat experience` = replace_na(
      `threat experience`,
      "don't know / no response")
  ) %>%
  
  mutate(sex = as_factor(v_geschlecht)) %>%
  mutate(sex = recode(
    sex,
    `divers` = "nonbinary",
    `weitere / other` = "nonbinary",
    `männlich` = "male", `weiblich` = "female",
    `weitere / andere` = "other"
  )) %>%
  
  mutate(`migration background` = ifelse(v_mig_background, "yes", "no")) %>%

  mutate(class = as_factor(v_schicht)) %>%
  mutate(
    class = recode(
      class,
      `Der Oberschicht` = "high",
      `Der oberen Mittelschicht` = "high",
      `Der Mittelschicht` = "medium",
      `Der unteren Mittelschicht` = "low",
      `Der Arbeiterschicht` = "low",
      `Der Unterschicht` = "low"
    )) %>%
  mutate(class = na_if(class, "Weiß nicht")) %>%
  mutate(class = droplevels(class)) %>%
  
  select(`threat experience`, sex, `migration background`, class) %>%
  mutate(across(everything(), as.vector)) %>%
  crosstable(
    by = `threat experience`,
    total = "row",
    percent_digits = 0,
    showNA = "no",
    percent_pattern = list(
      body = "{n}\n({p_row})",
      total_row = "{n}\n({p_row})",
      total_col = "{n}\n({p_row})",
      total_all = "{n}\n({p_row})"
    )
  )

threatened1 %>% as_flextable(keep_id = FALSE, compact = FALSE)
```


\newpage

## Threat experience by age

```{r, echo = FALSE}
threatened3 <- kommrep %>%
  filter(v_lastpage == 40) %>%
  select(v_bedrohung, v_alter) %>%
  
  mutate(`threat experience` = as_factor(v_bedrohung)) %>%
  mutate(`threat experience` = recode(
    `threat experience`, `Weiß nicht` = "don't know / no response")
  ) %>%
  
  mutate(`threat experience` = recode(
    `threat experience`,
    `Weiß nicht` = "don't know / no response",
    `Ja` = "yes", `Nein` = "no"
    )
  ) %>%
  
  filter(!is.na(v_alter)) %>%
  mutate(alter = 2022 - v_alter) %>%
  mutate(`age cohort` = as.character(trunc(alter / 10) * 10)) %>%
  mutate(
    `age cohort` = recode(
      `age cohort`,
      `10` = "10-19",
      `20` = "20-29",
      `30` = "30-39",
      `40` = "40-49",
      `50` = "50-59",
      `60` = "60-69",
      `70` = "70-79",
      `80` = "80-89",
      `90` = "90-99"
    )
  ) %>%
  
  select(`threat experience`, `age cohort`) %>%
  mutate(across(everything(), as.vector)) %>%
  crosstable(
    by = `threat experience`,
    total = "row",
    percent_digits = 0,
    showNA = "no",
  )

threatened3 %>% as_flextable(keep_id = FALSE, compact = FALSE)
```


\newpage

## Threat experience by party

```{r threat_by_party, echo = FALSE, results = "asis", fig.width = 6}
threatened6 <- kommrep_loc %>%
  select(v_bedrohung, v_part1) %>%
  mutate(`party` = as.character(as_factor(v_part1))) %>%
  mutate(`threat experience` = as_factor(v_bedrohung)) %>%
    mutate(`threat experience` = recode(
    `threat experience`,
    `Weiß nicht` = "don't know / no response",
    `Ja` = "yes", `Nein` = "no"
    )
  ) %>%
  mutate(
    `threat experience` = replace_na(
      `threat experience`,
      "don't know / no response")
  ) %>%
  mutate(threat = as_factor(v_bedrohung)) %>%
  select(`threat experience`, `party`) %>%
  mutate(across(everything(), as.vector)) %>%
  crosstable(
    by = `threat experience`,
    total = "none",
    percent_digits = 1,
    showNA = "no"
  )

threatened6 %>%
  as_flextable(
    keep_id = FALSE,
    compact = TRUE,
    fontsizes = list(body = 8, subheaders = 10, header = 10)
  )
```


\newpage

## Types of incivility by sex, class, migration background

```{r, echo = FALSE, fig.width = 8, warning = FALSE}
attacks <- kommrep_loc %>%
  
  select(starts_with("v_perzb_art"), v_geschlecht, v_mig_background, v_schicht, v_part1) %>%
  select(-v_perzb_art7, -v_perzb_art6) %>%
  
  mutate(across(starts_with("v_perzb_art"), as_factor)) %>%
  mutate(across(starts_with("v_perzb_art"), recode, `Trifft zu` = "yes", `Trifft nicht zu` = "no", `Weiß nicht` = "don't know / no reply")) %>%
  mutate(across(starts_with("v_perzb_art"), as.character)) %>%
  mutate(across(starts_with("v_perzb_art"), replace_na, "don't know / no reply")) %>%
  mutate(across(starts_with("v_perzb_art"), as.factor)) %>%
  
  mutate(sex = as_factor(v_geschlecht)) %>%
  mutate(sex = recode(sex, `divers` = "nonbinary", `weitere / other` = "nonbinary")) %>%
  
  mutate(`migration background` = ifelse(v_mig_background, "yes", "no")) %>%

  mutate(class = as_factor(v_schicht)) %>%
  mutate(
    class = recode(
      class,
      `Der Oberschicht` = "high",
      `Der oberen Mittelschicht` = "high",
      `Der Mittelschicht` = "medium",
      `Der unteren Mittelschicht` = "low",
      `Der Arbeiterschicht` = "low",
      `Der Unterschicht` = "low"
    )) %>%
  mutate(class = na_if(class, "Weiß nicht")) %>%
  mutate(class = droplevels(class)) %>%
  
  mutate(Partei = as.character(as_factor(v_part1))) %>%
  
  select(-v_geschlecht, -v_mig_background, -v_schicht, v_part1) %>%
  rename(
    LegacyComm = v_perzb_art1,
    SocMedia = v_perzb_art2,
    Encounter = v_perzb_art3,
    Damage = v_perzb_art4,
    Attack = v_perzb_art5
  ) %>%
  mutate(across(everything(), function(x) as.vector(x)))


what <- c("LegacyComm", "SocMedia", "Encounter", "Damage", "Attack")
ctbs <- lapply(
  what,
  function(var){
    attacks %>%
      select(all_of(var), sex, class, `migration background`) %>%
      crosstable(
        by = all_of(var),
        total = "both",
        percent_digits = 1,
        percent_pattern = list(
          body = "{n}\n({p_row})",
          total_row = "{n}\n({p_row})",
          total_col = "{n}\n({p_row})",
          total_all = "{n}\n({p_row})"
        ),
        showNA = "no"
      ) 
  }
)
names(ctbs) <- what

tab <- bind_cols(
  select(ctbs[[1]], -yes, -no, -`don't know / no reply`, -Total),
  as_tibble(as.data.frame(lapply(ctbs, `[[`, "yes"))),
  select(ctbs[[1]], Total)
)
total_row <- filter(tab, variable == "Total")[1,]
total_row[1,2:3] <- "Total"
tab <- bind_rows(
  filter(tab, variable != "Total"),
  total_row
)

as_flextable(
  tab,
  fontsizes = list(body = 8, subheaders = 8, header = 8)
)
```