---
title: "Threatened Representation"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
bibliography: literatur.bibtex
always_allow_html: true
classoption: landscape
editor_options: 
  chunk_output_type: console
---

```{r load_libraries, message = FALSE, echo = FALSE}
library(dplyr)
library(data.table)
library(xts)
library(haven)
library(magrittr)
library(tidyr)
library(xtable)
library(forcats)
library(scales)
library(crosstable)
library(stargazer)
library(jtools)
library(broom.mixed) # to avoid later msg of loading
library(ggplot2)
library(flextable)
library(officer)
library(scales)
library(stargazer)
library(openxlsx)
library(ggpubr)

library(kommrep)
stopifnot(packageVersion("kommrep") >= package_version("0.3.8"))
```

```{r set_options, include = FALSE}
set_flextable_defaults(pct_digits = "#")
options("modelsummary_format_numeric_latex" = "plain")
```


```{r make modified_table, echo = FALSE, results = "asis"}
source("~/Lab/github/incivility/aux/kommrep_loc_lm.R")
```


\newpage


## Types of behavioral change

```{r, echo = FALSE}
kommrep_loc %>%
  mutate(
    `behavior_considering exit` = ifelse(as.character(as_factor(v_exit)) == "Ja", TRUE, FALSE),
#    `behavior_avoid social media` = ifelse(v_sorge_umgang3 == 1L, TRUE, FALSE), # Verzicht auf soziale Medien
    `behavior_avoid topics` = ifelse(v_sorge_umgang4 == 1L, TRUE, FALSE) #  Zurückhaltung bei Themen
#     `behavior_avoid places` = ifelse(v_sorge_umgang5 == 1L, TRUE, FALSE)
  ) %>%
  select(starts_with("behavior_"), weight_ps) %>%
  pivot_longer(cols = starts_with("behavior")) %>%
  mutate(name = gsub("^behavior_(.*?)$", "\\1", name)) %>%
#  mutate(value = ifelse(is.na(value), FALSE, value)) %>%
  group_by(name, value) %>%
  summarise(n_weighed = sum(weight_ps)) %>%
  pivot_wider(names_from = value, values_from = n_weighed) %>%
  mutate(true_percent = round(`TRUE` / (`TRUE` + `FALSE` + `NA`) * 100, 1)) %>%
  mutate(false_percent = round(`FALSE` / (`TRUE` + `FALSE` + `NA`) * 100, 1)) %>%
  mutate(na_percent = round(`NA` / (`TRUE` + `FALSE` + `NA`) * 100, 1)) %>%
  mutate(name = factor(
    name,
    levels = c(
      "considering exit",
#      "avoid places",
#      "avoid social media",
      "avoid topics")
  )) %>%
#  tibble(category = c("responsiveness", "responsiveness", "substantive representation", "descriptive representation")) %>%
  select(- `FALSE`, -`TRUE`, -`NA`) %>%
  rename(
    `what` = "name",
    `true` = "true_percent",
    `false` = "false_percent",
    `na` = "na_percent"
  ) %>%
  pivot_longer(cols = c("true", "false", "na")) %>%
  ggplot(aes(x = what, y = value, fill = name)) +
    geom_bar(stat = "identity", position = "stack") + 
#    ylim(0, 12.5) +
    geom_text(
    aes(label = paste0(value, "%")),
    position = position_stack(0.5),    # move to center of bars
#     vjust = -1,    # nudge above top of bar
     size = 5, color = "white"
    ) + 
    xlab("Type of behavioral change") + 
    ylab("Share/percent (with case weights)")
    

ggsave("~/Lab/github/incivility/svg/behavioral_change.svg", width = 24, height = 12, units = "cm")
```


\newpage

```{r, echo = FALSE}
GENDER <- kommrep_loc %>%
  select(v_exit, v_geschlecht) %>%
  mutate(exit = ifelse(as.character(as_factor(v_exit)) == "Ja", TRUE, FALSE)) %>%
  mutate(gender = as_factor(v_geschlecht)) %>%
  mutate(gender = recode(
    gender,
    `männlich` = "male",
    `weiblich` = "female/nonbinary",
    `divers` = "female/nonbinary",
    `weitere / andere` = "female/nonbinary")
  ) %>%
  mutate(gender = factor(gender, levels = c("male", "female/nonbinary"))) %>%
  select(gender, `exit`) %>%
  group_by(gender, `exit`) %>%
  filter(!is.na(gender)) %>%
  summarise(N = n()) %>%
  group_by(gender) %>%
  group_split() %>%
  lapply(function(x) mutate(x, share = x$N / sum(x$N))) %>%
  bind_rows() %>%
  mutate(`exit` = ifelse(is.na(`exit`), "NA", `exit`)) %>%
  mutate(`exit` = factor(`exit`, levels = c("FALSE", "NA", "TRUE"))) %>%
  mutate(percent = round(share * 100, 1)) %>%
  ggplot(aes(x = gender, y = percent, fill = `exit`)) +
    geom_bar(stat = "identity", position = "stack") +
    geom_text(aes(label = paste(percent, "%")), position = position_stack(0.5), color = "white") +
    theme(axis.title.y = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

RACE <- kommrep_loc_lm %>%
  select(v_exit, racialized) %>%
  mutate(exit = ifelse(as.character(as_factor(v_exit)) == "Ja", TRUE, FALSE)) %>%
  mutate(`racialized` = ifelse(racialized, "yes", "no")) %>%
  filter(!is.na(`racialized`)) %>%
  group_by(`racialized`, `exit`) %>%
  summarise(N = n()) %>%
  group_by(`racialized`) %>%
  group_split() %>%
  lapply(function(x) mutate(x, share = x$N / sum(x$N))) %>%
  bind_rows() %>%
  mutate(`exit` = ifelse(is.na(`exit`), "NA", `exit`)) %>%
  mutate(`exit` = factor(`exit`, levels = c("FALSE", "NA", "TRUE"))) %>%
  mutate(percent = round(share * 100, 1)) %>%
  ggplot(aes(x = `racialized`, y = percent, fill = `exit`)) +
    geom_bar(stat = "identity", position = "stack") +
    geom_text(aes(label = paste(percent, "%")), position = position_stack(0.5), color = "white") 

CLASS <- kommrep_loc %>%
  select(v_exit, v_schicht) %>%
  mutate(exit = ifelse(as.character(as_factor(v_exit)) == "Ja", TRUE, FALSE)) %>%
  mutate(`class` = as_factor(v_schicht)) %>%
  mutate(
    `class` = recode(
      `class`,
      `Der Oberschicht` = "upper",
      `Der oberen Mittelschicht` = "upper",
      `Der Mittelschicht` = "middle",
      `Der unteren Mittelschicht` = "low",
      `Der Arbeiterschicht` = "low",
      `Der Unterschicht` = "low"
    )) %>%
  mutate(`class` = na_if(`class`, "Weiß nicht")) %>%
  filter(!is.na(class)) %>%
  mutate(`class` = droplevels(`class`)) %>%
  select(`exit`, `class`) %>%
  group_by(`class`, `exit`) %>%
  summarise(N = n()) %>%
  group_by(`class`) %>%
  group_split() %>%
  lapply(function(x) mutate(x, share = x$N / sum(x$N))) %>%
  bind_rows() %>%
  mutate(`exit` = ifelse(is.na(`exit`), "NA", `exit`)) %>%
  mutate(`exit` = factor(`exit`, levels = c("FALSE", "NA", "TRUE"))) %>%
  mutate(percent = round(share * 100, 1)) %>%
  ggplot(aes(x = `class`, y = percent, fill = `exit`)) +
    geom_bar(stat = "identity", position = "stack") +
    geom_text(aes(label = paste(percent, "%")), position = position_stack(0.5), color = "white")  +
    theme(axis.title.y = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

ggarrange(RACE, GENDER, CLASS, common.legend = TRUE, nrow = 1)

ggsave("~/Lab/github/incivility/svg/considering_exit_by_group.svg", width = 24, height = 12, units = "cm")
```


\newpage

## Avoiding topics

```{r, echo = FALSE}
GENDER <- kommrep_loc %>%
  select(v_sorge_umgang4, v_geschlecht) %>%
  mutate(`avoid topics` = ifelse(v_sorge_umgang4 == 1L, TRUE, FALSE)) %>%
  mutate(gender = as_factor(v_geschlecht)) %>%
  mutate(gender = recode(
    gender,
    `männlich` = "male",
    `weiblich` = "female/nonbinary",
    `divers` = "female/nonbinary",
    `weitere / andere` = "female/nonbinary")
  ) %>%
  mutate(gender = factor(gender, levels = c("male", "female/nonbinary"))) %>%
  select(gender, `avoid topics`) %>%
  group_by(gender, `avoid topics`) %>%
  filter(!is.na(gender)) %>%
  summarise(N = n()) %>%
  group_by(gender) %>%
  group_split() %>%
  lapply(function(x) mutate(x, share = x$N / sum(x$N))) %>%
  bind_rows() %>%
  mutate(`avoid topics` = ifelse(is.na(`avoid topics`), "NA", `avoid topics`)) %>%
  mutate(`avoid topics` = factor(`avoid topics`, levels = c("FALSE", "NA", "TRUE"))) %>%
  mutate(percent = round(share * 100, 1)) %>%
  ggplot(aes(x = gender, y = percent, fill = `avoid topics`)) +
    geom_bar(stat = "identity", position = "stack") +
    geom_text(aes(label = paste(percent, "%")), position = position_stack(0.5), color = "white") +
    theme(axis.title.y = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

RACE <- kommrep_loc_lm %>%
  select(v_sorge_umgang4, racialized) %>%
  mutate(`avoid topics` = ifelse(v_sorge_umgang4 == 1L, TRUE, FALSE)) %>%
  mutate(`racialized` = ifelse(racialized, "yes", "no")) %>%
  filter(!is.na(`racialized`)) %>%
  group_by(`racialized`, `avoid topics`) %>%
  summarise(N = n()) %>%
  group_by(`racialized`) %>%
  group_split() %>%
  lapply(function(x) mutate(x, share = x$N / sum(x$N))) %>%
  bind_rows() %>%
  mutate(`avoid topics` = ifelse(is.na(`avoid topics`), "NA", `avoid topics`)) %>%
  mutate(`avoid topics` = factor(`avoid topics`, levels = c("FALSE", "NA", "TRUE"))) %>%
  mutate(percent = round(share * 100, 1)) %>%
  ggplot(aes(x = `racialized`, y = percent, fill = `avoid topics`)) +
    geom_bar(stat = "identity", position = "stack") +
    geom_text(aes(label = paste(percent, "%")), position = position_stack(0.5), color = "white") 

CLASS <- kommrep_loc %>%
  select(v_sorge_umgang4, v_schicht) %>%
  mutate(`avoid topics` = ifelse(v_sorge_umgang4 == 1L, TRUE, FALSE)) %>%
  mutate(`class` = as_factor(v_schicht)) %>%
  mutate(
    `class` = recode(
      `class`,
      `Der Oberschicht` = "upper",
      `Der oberen Mittelschicht` = "upper",
      `Der Mittelschicht` = "middle",
      `Der unteren Mittelschicht` = "low",
      `Der Arbeiterschicht` = "low",
      `Der Unterschicht` = "low"
    )) %>%
  mutate(`class` = na_if(`class`, "Weiß nicht")) %>%
  filter(!is.na(class)) %>%
  mutate(`class` = droplevels(`class`)) %>%
  select(`avoid topics`, `class`) %>%
  group_by(`class`, `avoid topics`) %>%
  summarise(N = n()) %>%
  group_by(`class`) %>%
  group_split() %>%
  lapply(function(x) mutate(x, share = x$N / sum(x$N))) %>%
  bind_rows() %>%
  mutate(`avoid topics` = ifelse(is.na(`avoid topics`), "NA", `avoid topics`)) %>%
  mutate(`avoid topics` = factor(`avoid topics`, levels = c("FALSE", "NA", "TRUE"))) %>%
  mutate(percent = round(share * 100, 1)) %>%
  ggplot(aes(x = `class`, y = percent, fill = `avoid topics`)) +
    geom_bar(stat = "identity", position = "stack") +
    geom_text(aes(label = paste(percent, "%")), position = position_stack(0.5), color = "white")  +
    theme(axis.title.y = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

ggarrange(RACE, GENDER, CLASS, common.legend = TRUE, nrow = 1)

ggsave("~/Lab/github/incivility/svg/avoiding_topics_by_group.svg", width = 24, height = 12, units = "cm")
```


