---
title: "Threatened Representation"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
bibliography: literatur.bibtex
always_allow_html: true
classoption: landscape
editor_options: 
  chunk_output_type: console
---

```{r load_libraries, message = FALSE, echo = FALSE}
library(dplyr)
library(data.table)
library(xts)
library(haven)
library(magrittr)
library(tidyr)
library(xtable)
library(forcats)
library(scales)
library(crosstable)
library(stargazer)
library(jtools)
library(broom.mixed) # to avoid later msg of loading
library(ggplot2)
library(ggpubr)
library(flextable)
library(officer)
library(scales)
library(stargazer)
library(openxlsx)

library(kommrep)
stopifnot(packageVersion("kommrep") >= package_version("0.3.8"))
```

```{r set_options, include = FALSE}
set_flextable_defaults(pct_digits = "#")
options("modelsummary_format_numeric_latex" = "plain")
```


```{r make modified_table, echo = FALSE, results = "asis"}
source("~/Lab/github/incivility/aux/kommrep_loc_lm.R")
```


```{r threat_and_change, echo = FALSE}
behavioral_change <- kommrep_loc %>%
  select(v_bedrohung, v_sorge_umgang1) %>% # Verhaltensänderung? 1504 1=Ja!
  filter(v_bedrohung != 98) %>%
  mutate(`behavioral change` = ifelse(as.vector(v_sorge_umgang1) == 0L, "yes", "no")) %>%
  mutate(`threat experience` = ifelse(as.vector(v_bedrohung) == 1L, "yes", "no")) %>%
  crosstable(
    `threat experience`, by = `behavioral change`,
    percent_pattern = list(
      body = "{p_row}\n({n})",
      total_row = "{p_row}\n({n})",
      total_col = "{p_row}\n({n})",
      total_all = "{p_row}\n({n})"
    ),
    total = "both", percent_digits = 1)


behavioral_change %>% as_flextable(keep_id = FALSE, compact = TRUE)
```

\newpage

## Expected and experienced threats and behavioral change

```{r threat_and_change2, echo = FALSE}
behavioral_change <- kommrep_loc_lm %>%
  select(threat_experience, threat_verbal, threat_physical, behavioral_change) %>% # Verhaltensänderung? 1504 1=Ja!
  
  mutate(`threat experienced` = ifelse(threat_experience, "yes", "no")) %>%
  mutate(`communicative threat` = ifelse(threat_verbal > 0, "yes", "no")) %>% 
  mutate(`physical threat` = ifelse(threat_physical > 0, "yes", "no")) %>% 
           
  mutate(`behavioral change` = ifelse(behavioral_change > 0, "yes", "no")) %>%
  
  select(`threat experienced`, `communicative threat`, `physical threat`, `behavioral change`) %>% 
  crosstable(
    by = `behavioral change`,
    percent_digits = 1,
    showNA = "no",
    percent_pattern = list(
      body = "{p_row}\n({n})",
      total_row = "{p_row}\n({n})",
      total_col = "{p_row}\n({n})",
      total_all = "{p_row}\n({n})"
    ),
    total = "none",
  )

behavioral_change %>% as_flextable(keep_id = FALSE, compact = FALSE)
```


```{r threat_and_change2, echo = FALSE}
threat_and_change <- kommrep_loc_lm %>%
  select(threat_experience, threat_verbal, threat_physical, behavioral_change) %>% # Verhaltensänderung? 1504 1=Ja!
  mutate(`threat experienced` = ifelse(threat_experience, "yes", "no")) %>%
  mutate(`communicative threat` = ifelse(threat_verbal > 0, "yes", "no")) %>% 
  mutate(`physical threat` = ifelse(threat_physical > 0, "yes", "no")) %>% 
  mutate(`behavioral change` = ifelse(behavioral_change > 0, "yes", "no")) %>%
  select(`threat experienced`, `communicative threat`, `physical threat`, `behavioral change`)


lapply(
  c("communicative threat", "physical threat", "threat experienced"),
  function(threat){
    select(threat_and_change, `behavioral change`, !!threat) %>%
     group_by_all() %>%
      summarise(N = n()) %>%
      mutate(threat = !!threat) %>%
      rename("value" = !!threat) %>%
      filter(!is.na(value))
  }
) %>%
  bind_rows() %>% 
  filter(!is.na(value)) %>%
  group_by(`threat`, `value`) %>%
  group_split() %>%
  lapply(function(x) mutate(x, share = x$N / sum(x$N))) %>%
  bind_rows() %>%
  mutate(percent = round(share * 100, 1)) %>%
  ggplot(aes(x = `value`, y = percent, fill = `behavioral change`)) +
    geom_bar(position = "stack", stat = "identity") +
    facet_wrap(~ threat) +
    geom_text(
      aes(label = sprintf("%s\n[%s]", paste(percent, "%"), N)),
      position = position_stack(0.5),
      color = "white"
    )

ggsave("~/Lab/github/incivility/svg/threat_and_behavioral_change.svg", width = 24, height = 12, units = "cm")
```

\newpage

**Tabelle 13: Behavioral Change by Group**

```{r, echo = FALSE}
change_who <- kommrep_loc %>%
  
  select(v_sorge_umgang1, v_geschlecht, v_mig_background, v_schicht) %>%
  
  mutate(`behavioral change` = ifelse(v_sorge_umgang1 == 0, "yes", "no")) %>%

  mutate(sex = as_factor(v_geschlecht)) %>%
  mutate(sex = recode(sex, `männlich` = "male", `weiblich` = "female", `divers` = "nonbinary", `weitere / andere` = "nonbinary")) %>%
  
  mutate(`migration background` = ifelse(v_mig_background, "yes", "no")) %>%

  mutate(`class` = as_factor(v_schicht)) %>%
  mutate(
    `class` = recode(
      `class`,
      `Der Oberschicht` = "high",
      `Der oberen Mittelschicht` = "high",
      `Der Mittelschicht` = "medium",
      `Der unteren Mittelschicht` = "low",
      `Der Arbeiterschicht` = "low",
      `Der Unterschicht` = "low"
    )) %>%
  mutate(`class` = na_if(`class`, "Weiß nicht")) %>%
  mutate(`class` = droplevels(`class`)) %>%
  
  select(`behavioral change`, sex, `migration background`, `class`) %>%
  mutate(across(everything(), as.vector)) %>%
  crosstable(by = `behavioral change`, total = "none", percent_digits = 1, showNA = "no")

change_who %>% as_flextable(keep_id = FALSE, compact = FALSE)
```
