---
title: "Threatened Representation"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
bibliography: literatur.bibtex
always_allow_html: true
classoption: landscape
editor_options: 
  chunk_output_type: console
---

\newpage

```{r load_libraries, message = FALSE, echo = FALSE}
library(dplyr)
library(data.table)
library(xts)
library(haven)
library(magrittr)
library(tidyr)
library(xtable)
library(forcats)
library(scales)
library(crosstable)
library(stargazer)
library(jtools)
library(broom.mixed) # to avoid later msg of loading
library(ggplot2)
library(flextable)
library(officer)
library(scales)
library(stargazer)
library(openxlsx)

library(kommrep)
stopifnot(packageVersion("kommrep") >= package_version("0.3.8"))
```

```{r set_options, echo = FALSE, include = FALSE}
set_flextable_defaults(pct_digits = "#")
options("modelsummary_format_numeric_latex" = "plain")
```

```{r make modified_table, echo = FALSE, results = "asis"}
source("~/Lab/github/incivility/aux/kommrep_loc_lm.R")
```



```{r descriptive_representation, results = "asis", echo = FALSE}
stay1 <- glm(
  stay ~ threat_verbal + threat_physical,
  data = kommrep_loc_lm,
  family = binomial("logit")
)

stay2 <- glm(
  stay ~ threat_verbal + threat_physical + age + AfD + SPD + GRUENE + LINKE,
  data = kommrep_loc_lm,
  family = binomial("logit")
)


stay3 <- glm(
  stay ~ threat_verbal + threat_physical + age + AfD + SPD + GRUENE + LINKE + female_diverse + class,
  data = kommrep_loc_lm,
  family = binomial("logit")
)

stay4 <- glm(
  stay ~ threat_verbal + threat_physical + age + AfD + SPD + GRUENE + LINKE + female_diverse + class + racialized,
  data = kommrep_loc_lm,
  family = binomial("logit")
)

stay5 <- glm(
  stay ~ threat_verbal + threat_physical + age + AfD + SPD + GRUENE + LINKE + female_diverse + class + racialized + soc + gen + div,
  data = kommrep_loc_lm,
  family = binomial("logit")
)

modelsummary::modelsummary(
  models = list(
    A = stay1,
    B = stay2,
    C = stay3,
    D = stay4,
    E = stay5
  ),
  estimate = "{estimate} ({std.error}){stars}",
  statistic = NULL,
  output = "latex",
  coef_map = c(
    "threat_verbal" = "Communicative threat ",
    "threat_physical" = "Physical threat",
    "racializedTRUE" = "Racialized group (Ref. no)",
    "female_diverseTRUE" = "Female or diverse (Ref. no)",
    "class" = "Class",
    "divTRUE" = "Primary Topic: Migration",
    "genTRUE" = "Primary Topic: Gender",
    "socTRUE" = "Primary Topic: Class",
    "AfDTRUE" = "AfD (Ref. other)",
    "SPDTRUE" = "SPD",
    "GRUENETRUE" = "B'90/Grüne",
    "LINKETRUE" = "LINKE",
    "age" = "Age",
    "(Intercept)" = "(Intercept)"
  ),
  stars = c('*' = .05, '**' = .01, '***' = .001),
  title = "Descriptive representation: Determinants of certainty to stay"
  # , gof_omit = "BIC|AIC|RMSE|Log.Lik|F"
)
```


\newpage

## Coefficient plot: Certainty to stay

```{r, echo = FALSE}
plot_summs(stay1, stay2, stay3, stay4, stay5, colors = "Qual1")
```


\newpage

```{r, results = "asis", echo = FALSE}
behavior1 <- glm(
  muted2 ~ threat_verbal + threat_physical,
  data = kommrep_loc_lm,
  family = binomial("logit")
)

behavior2 <- glm(
  muted2 ~ threat_verbal + threat_physical + age + AfD + SPD + GRUENE + LINKE,
  data = kommrep_loc_lm,
  family = binomial("logit")
)


behavior3 <- glm(
  muted2 ~ threat_verbal + threat_physical + age + AfD + SPD + GRUENE + LINKE + female_diverse + class,
  data = kommrep_loc_lm,
  family = binomial("logit")
)

behavior4 <- glm(
  muted2 ~ threat_verbal + threat_physical + age + AfD + SPD + GRUENE + LINKE + female_diverse + class + racialized,
  data = kommrep_loc_lm,
  family = binomial("logit")
)


behavior5 <- glm(
  muted2 ~ threat_verbal + threat_physical + age + AfD + SPD + GRUENE + LINKE + female_diverse + class + racialized + soc + gen + div,
  data = kommrep_loc_lm,
  family = binomial("logit")
)


modelsummary::modelsummary(
  models = list(A = behavior1, B = behavior2, C = behavior3, D = behavior4, E = behavior5),
  estimate = "{estimate} ({std.error}){stars}",
  statistic = NULL,
  output = "latex",
  coef_map = c(
    "threat_verbal" = "Communicative threat",
    "threat_physical" = "Physical threat",
    "racializedTRUE" = "Racialized group (Ref. no)",
    "female_diverseTRUE" = "Female or diverse (Ref. no)",
    "class" = "Class",
    "divTRUE" = "Primary Topic: Migration",
    "genTRUE" = "Primary Topic: Gender",
    "socTRUE" = "Primary Topic: Class",
    "AfDTRUE" = "AfD (Ref. other)",
    "SPDTRUE" = "SPD",
    "GRUENETRUE" = "B'90/Grüne",
    "LINKETRUE" = "LINKE",
    "age" = "Age",
    "(Intercept)" = "(Intercept)"
  ),
  stars = c('*' = .05, '**' = .01, '***' = .001),
  title = "Regression results: Muted substantial representation"
#  , gof_omit = "BIC|AIC|RMSE|Log.Lik|F"
)
```


\newpage

## Coefficient plot: Muted substantial representation

```{r, echo = FALSE, }
plot_summs(behavior1, behavior2, behavior3, behavior4, behavior5, colors = "Qual1")
```


